services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bibliotrace_v3
      MYSQL_USER: admin
      MYSQL_PASSWORD: Bibl!otrace_2025
    ports:
      - "3306:3306"

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_container
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory"]
    ports:
      - "8000:8000"

  bibliotrace:
    platform: linux/amd64
    build: .
    container_name: bibliotrace
    restart: always
    depends_on:
      - mysql
      - dynamodb
    ports:
      - "8080:8080"
    env_file: ./.env
    environment:
      NODE_ENV: local
      DYNAMO_ENDPOINT: http://dynamodb:8000
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: Bibl!otrace_2025
    volumes:
      - .:/app
