services:
  mysql:
    image: mysql:9
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bibliotrace_v3
      MYSQL_USER: admin
      MYSQL_PASSWORD: Bibl!otrace_2025
    ports:
      - "3306:3306"

  bibliotrace:
    platform: linux/amd64
    build: .
    container_name: bibliotrace
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file: ./.env
    environment:
      NODE_ENV: local
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: Bibl!otrace_2025
    volumes:
      - .:/app
